/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LobbyImport } from './routes/lobby'
import { Route as IndexImport } from './routes/index'
import { Route as RoomSessionIdImport } from './routes/room.$sessionId'

// Create/Update Routes

const LobbyRoute = LobbyImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomSessionIdRoute = RoomSessionIdImport.update({
  id: '/room/$sessionId',
  path: '/room/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyImport
      parentRoute: typeof rootRoute
    }
    '/room/$sessionId': {
      id: '/room/$sessionId'
      path: '/room/$sessionId'
      fullPath: '/room/$sessionId'
      preLoaderRoute: typeof RoomSessionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lobby' | '/room/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lobby' | '/room/$sessionId'
  id: '__root__' | '/' | '/lobby' | '/room/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyRoute: typeof LobbyRoute
  RoomSessionIdRoute: typeof RoomSessionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyRoute: LobbyRoute,
  RoomSessionIdRoute: RoomSessionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lobby",
        "/room/$sessionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lobby": {
      "filePath": "lobby.tsx"
    },
    "/room/$sessionId": {
      "filePath": "room.$sessionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
